# Generated by Django 4.0.2 on 2022-02-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='modified_at',
        ),
    ]
